DEFAULT_PERMISSIONS = {
    "admin": {
        "product": ["view", "create", "update", "delete", "import", "export"],
        "customer": ["view", "create", "update", "delete", "import", "export"],
        "warehouse": ["view", "create", "update", "delete", "import", "export"],
        "uom": ["view", "create", "update", "delete", "import", "export"],
        "template": ["view", "create", "update", "delete", "print", "import", "export"],
        "order": ["view", "create", "update", "delete", "approve", "confirm", "print"],
        "wms": ["view", "create", "update", "scan", "dispatch", "print", "approve"],
        "document": ["view", "create", "print"],
        "user": ["view", "create", "update", "delete"],
        "permission": ["view", "update"],
        "inventory": ["view", "create", "update", "cycle_count", "approve_count"],
        "reports": ["view", "export"],
        "label": ["view", "generate"],
        "transfer": ["view", "create", "update", "approve", "reject", "complete", "cancel"],
        "entity": ["view", "create", "update", "delete"],
        "price_approval": ["view", "create", "update", "delete", "approve", "reject"],
        "tax_invoice": ["view", "create", "update", "replace", "cancel", "print"],
        "sales_return": ["view", "create", "update", "approve", "reject"],
        "approval": ["view", "approve"],
        "settings": ["view", "manage"],
        "supplier": ["view", "create", "update", "delete"],
        "cash": ["view", "create", "delete"],
        "purchase_order": ["view", "create", "update", "approve", "reject"],
        "purchase_return": ["view", "create", "update", "approve", "reject"],
        "purchase_requisition": ["view", "create", "update", "approve", "reject"],
        "vendor_bill": ["view", "create", "update", "approve", "reject", "pay"],
        "landed_cost": ["view", "create", "update", "approve", "reject", "pay"],
        "input_tax": ["view", "create", "cancel"],
        "rfq": ["view", "create", "update", "award"],
        "ar_receipt": ["view", "create", "void"],
        "accounting": ["view", "create", "void", "manage"],
        "pricelist": ["view", "manage"],
    },
    "sales": {
        "product": ["view"],
        "customer": ["view", "create", "update"],
        "warehouse": ["view"],
        "uom": ["view"],
        "template": ["view"],
        "order": ["view", "create", "update", "print"],
        "document": ["view", "create", "print"],
        "inventory": ["view"],
        "price_approval": ["view", "create", "update"],
        "tax_invoice": ["view", "create", "print"],
        "sales_return": ["view", "create", "update"],
        "ar_receipt": ["view", "create"],
        "pricelist": ["view"],
    },
    "manager": {
        "product": ["view", "export"],
        "customer": ["view", "create", "update", "export"],
        "warehouse": ["view", "export"],
        "uom": ["view"],
        "template": ["view"],
        "order": ["view", "create", "update", "approve", "confirm", "print"],
        "wms": ["view", "create", "update", "scan", "dispatch", "print", "approve"],
        "document": ["view", "create", "print"],
        "inventory": ["view", "cycle_count", "approve_count", "update"],
        "reports": ["view", "export"],
        "label": ["view", "generate"],
        "transfer": ["view", "create", "approve", "reject", "complete"],
        "entity": ["view"],
        "price_approval": ["view", "create", "update", "approve", "reject"],
        "tax_invoice": ["view", "create", "update", "replace", "cancel", "print"],
        "sales_return": ["view", "create", "update", "approve", "reject"],
        "approval": ["view", "approve"],
        "settings": ["view"],
        "supplier": ["view", "create", "update", "delete"],
        "cash": ["view", "create", "delete"],
        "purchase_order": ["view", "create", "update", "approve", "reject"],
        "purchase_return": ["view", "create", "update", "approve", "reject"],
        "purchase_requisition": ["view", "create", "update", "approve", "reject"],
        "vendor_bill": ["view", "create", "update", "approve", "reject", "pay"],
        "landed_cost": ["view", "create", "update", "approve", "reject", "pay"],
        "input_tax": ["view", "create", "cancel"],
        "rfq": ["view", "create", "update", "award"],
        "ar_receipt": ["view", "create", "void"],
        "accounting": ["view", "create", "void", "manage"],
        "pricelist": ["view", "manage"],
    },
    "warehouse": {
        "product": ["view"],
        "warehouse": ["view"],
        "uom": ["view"],
        "template": ["view"],
        "order": ["view"],
        "wms": ["view", "create", "update", "scan", "dispatch", "print"],
        "document": ["view", "create", "print"],
        "inventory": ["view", "cycle_count", "update"],
        "label": ["view", "generate"],
        "transfer": ["view", "create", "update"],
        "purchase_order": ["view"],
        "purchase_return": ["view", "create"],
        "purchase_requisition": ["view", "create", "update"],
        "vendor_bill": ["view"],
        "landed_cost": ["view"],
        "input_tax": ["view"],
        "rfq": ["view", "create", "update"],
    },
}
